{"uid":"9a00cad8bc0e169f","name":"Create a new task -- @1.1 ","fullName":"Create a new task functionallity: Create a new task","historyId":"8a771a5082802af253ff19f7d6ade175","time":{"start":1732867403758,"stop":1732867664268,"duration":260510},"status":"broken","statusMessage":"selenium.common.exceptions.WebDriverException: Message: Unable to communicate to node\n\n","statusTrace":"  File \"/home/runner/.cache/pypoetry/virtualenvs/todoist-test-Iz2mgPfl-py3.11/lib/python3.11/site-packages/behave/model.py\", line 1329, in run\n    match.run(runner.context)\n  File \"/home/runner/.cache/pypoetry/virtualenvs/todoist-test-Iz2mgPfl-py3.11/lib/python3.11/site-packages/behave/matchers.py\", line 98, in run\n    self.func(context, *args, **kwargs)\n  File \"tests/ui/steps/login_steps.py\", line 8, in step_navigate_to_login_page\n    context.login_page.load()\n  File \"/home/runner/work/todoist-testing/todoist-testing/tests/ui/pages/base_page.py\", line 11, in load\n    self.driver.get(self.url)\n  File \"/home/runner/.cache/pypoetry/virtualenvs/todoist-test-Iz2mgPfl-py3.11/lib/python3.11/site-packages/selenium/webdriver/remote/webdriver.py\", line 393, in get\n    self.execute(Command.GET, {\"url\": url})\n  File \"/home/runner/.cache/pypoetry/virtualenvs/todoist-test-Iz2mgPfl-py3.11/lib/python3.11/site-packages/selenium/webdriver/remote/webdriver.py\", line 384, in execute\n    self.error_handler.check_response(response)\n  File \"/home/runner/.cache/pypoetry/virtualenvs/todoist-test-Iz2mgPfl-py3.11/lib/python3.11/site-packages/selenium/webdriver/remote/errorhandler.py\", line 232, in check_response\n    raise exception_class(message, screen, stacktrace)\n","flaky":false,"newFailed":false,"newBroken":false,"newPassed":false,"retriesCount":0,"retriesStatusChange":false,"beforeStages":[],"testStage":{"status":"broken","statusMessage":"selenium.common.exceptions.WebDriverException: Message: Unable to communicate to node\n\n","statusTrace":"  File \"/home/runner/.cache/pypoetry/virtualenvs/todoist-test-Iz2mgPfl-py3.11/lib/python3.11/site-packages/behave/model.py\", line 1329, in run\n    match.run(runner.context)\n  File \"/home/runner/.cache/pypoetry/virtualenvs/todoist-test-Iz2mgPfl-py3.11/lib/python3.11/site-packages/behave/matchers.py\", line 98, in run\n    self.func(context, *args, **kwargs)\n  File \"tests/ui/steps/login_steps.py\", line 8, in step_navigate_to_login_page\n    context.login_page.load()\n  File \"/home/runner/work/todoist-testing/todoist-testing/tests/ui/pages/base_page.py\", line 11, in load\n    self.driver.get(self.url)\n  File \"/home/runner/.cache/pypoetry/virtualenvs/todoist-test-Iz2mgPfl-py3.11/lib/python3.11/site-packages/selenium/webdriver/remote/webdriver.py\", line 393, in get\n    self.execute(Command.GET, {\"url\": url})\n  File \"/home/runner/.cache/pypoetry/virtualenvs/todoist-test-Iz2mgPfl-py3.11/lib/python3.11/site-packages/selenium/webdriver/remote/webdriver.py\", line 384, in execute\n    self.error_handler.check_response(response)\n  File \"/home/runner/.cache/pypoetry/virtualenvs/todoist-test-Iz2mgPfl-py3.11/lib/python3.11/site-packages/selenium/webdriver/remote/errorhandler.py\", line 232, in check_response\n    raise exception_class(message, screen, stacktrace)\n","steps":[{"name":"Given the user navigates to the login page","time":{"start":1732867403759,"stop":1732867664267,"duration":260508},"status":"broken","statusMessage":"selenium.common.exceptions.WebDriverException: Message: Unable to communicate to node\n\n","statusTrace":"  File \"/home/runner/.cache/pypoetry/virtualenvs/todoist-test-Iz2mgPfl-py3.11/lib/python3.11/site-packages/behave/model.py\", line 1329, in run\n    match.run(runner.context)\n  File \"/home/runner/.cache/pypoetry/virtualenvs/todoist-test-Iz2mgPfl-py3.11/lib/python3.11/site-packages/behave/matchers.py\", line 98, in run\n    self.func(context, *args, **kwargs)\n  File \"tests/ui/steps/login_steps.py\", line 8, in step_navigate_to_login_page\n    context.login_page.load()\n  File \"/home/runner/work/todoist-testing/todoist-testing/tests/ui/pages/base_page.py\", line 11, in load\n    self.driver.get(self.url)\n  File \"/home/runner/.cache/pypoetry/virtualenvs/todoist-test-Iz2mgPfl-py3.11/lib/python3.11/site-packages/selenium/webdriver/remote/webdriver.py\", line 393, in get\n    self.execute(Command.GET, {\"url\": url})\n  File \"/home/runner/.cache/pypoetry/virtualenvs/todoist-test-Iz2mgPfl-py3.11/lib/python3.11/site-packages/selenium/webdriver/remote/webdriver.py\", line 384, in execute\n    self.error_handler.check_response(response)\n  File \"/home/runner/.cache/pypoetry/virtualenvs/todoist-test-Iz2mgPfl-py3.11/lib/python3.11/site-packages/selenium/webdriver/remote/errorhandler.py\", line 232, in check_response\n    raise exception_class(message, screen, stacktrace)\n","steps":[],"attachments":[],"parameters":[],"shouldDisplayMessage":true,"stepsCount":0,"attachmentsCount":0,"hasContent":true,"attachmentStep":false},{"name":"When the user logs in with valid credentials","time":{"start":1732867664268,"stop":1732867664268,"duration":0},"status":"skipped","steps":[],"attachments":[],"parameters":[],"shouldDisplayMessage":false,"stepsCount":0,"attachmentsCount":0,"hasContent":false,"attachmentStep":false},{"name":"When the user click the add task button","time":{"start":1732867664268,"stop":1732867664268,"duration":0},"status":"skipped","steps":[],"attachments":[],"parameters":[],"shouldDisplayMessage":false,"stepsCount":0,"attachmentsCount":0,"hasContent":false,"attachmentStep":false},{"name":"When the user creates \"2\" tasks","time":{"start":1732867664268,"stop":1732867664268,"duration":0},"status":"skipped","steps":[],"attachments":[],"parameters":[],"shouldDisplayMessage":false,"stepsCount":0,"attachmentsCount":0,"hasContent":false,"attachmentStep":false}],"attachments":[],"parameters":[],"shouldDisplayMessage":false,"stepsCount":4,"attachmentsCount":0,"hasContent":true,"attachmentStep":false},"afterStages":[],"labels":[{"name":"severity","value":"normal"},{"name":"tag","value":"task"},{"name":"feature","value":"Create a new task functionallity"},{"name":"framework","value":"behave"},{"name":"language","value":"cpython3"},{"name":"resultFormat","value":"allure2"}],"parameters":[{"name":"number","value":"2"}],"links":[],"hidden":false,"retry":false,"extra":{"severity":"normal","retries":[],"categories":[{"name":"Test defects","matchedStatuses":[],"flaky":false}],"tags":["task"]},"source":"9a00cad8bc0e169f.json","parameterValues":["2"]}